theme = "0_gruvbox_dark_hard"

[editor]
color-modes = true
# Dvorak
jump-label-alphabet = "uhetonasidplrycfgxbkmjwqvz"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
A-ret = "goto_word"
"X" = ["extend_line_up", "extend_to_line_bounds"]

# move/copy line below/above
"A-down" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-up" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
"A-S-down" = [ "extend_to_line_bounds", "yank", "paste_after" ]
"A-S-up" = [ "extend_to_line_bounds", "yank", "paste_before" ]

# previous/next buffer
H = "goto_previous_buffer"
L = "goto_next_buffer"

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
